- name: Secure MySQL Setup using Ansible Vault
  hosts: all
  become: true
  vars_files:
    - vars/vault.yaml

  tasks:

    - name: Install MariaDB 10.11 server on Amazon Linux 2023
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    - name: Start and enable MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Set MySQL root password
      ansible.builtin.shell: |
        mysqladmin -u root password '{{ mysql_root_password }}'
      args:
        creates: /var/lib/mysql/mysql

    - name: Copy DB creation script
      ansible.builtin.template:
        src: templates/create_db.sql.j2
        dest: /tmp/create_db.sql

    - name: Create iVolve DB and user
      ansible.builtin.shell: |
        mysql -u root -p'{{ mysql_root_password }}' < /tmp/create_db.sql

    - name: "Validate: List MySQL databases using new user"
      ansible.builtin.shell: |
        mysql -u {{ db_user }} -p'{{ db_user_password }}' -e "SHOW DATABASES;"
      register: db_output

    - name: Print validation result
      debug:
        msg: "{{ db_output.stdout }}"

